version: "3"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "SqlServer2020@%"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"