version: '3.4'

services:
  starterproject:
    image: ${DOCKER_REGISTRY-}starterproject
    build:
      context: .
      dockerfile: StarterProject/Dockerfile

    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: ${SQL_PASSWORD}
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
    redis:
        image: redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
           - "6379:6379"

